### ISSUE TITLE
Error on delegate

### ISSUE THREAD

**Issue by gbunea** [cosmos/testnets#136]
I did the following steps:

1. **withdraw rewards by running:** _gaiacli tx distr withdraw-rewards cosmosvaloper1ktcwmkrgamuhfqm78mwy0py8a0uy5mddhkn0hg --from=syncnode --gas=auto --gas-adjustment=1.1 --commission --trust-node=true --chain-id=gaia-13001_ 
output OK

2. **checked wallet balance:** _gaiacli q account cosmos1ktcwmkrgamuhfqm78mwy0py8a0uy5mddjz86mm --trust-node=true_ 
output: 
Vesting Account:
  Address:          cosmos1ktcwmkrgamuhfqm78mwy0py8a0uy5mddjz86mm
  Pubkey:           cosmospub1addwnpepq2ezwyq6hpz69ls3fzr53n5ed6qplyzpdpl4w0n3lyndgvwpjcu5kqqlm5x
  Coins:            166169358muon,10182911870photino
  AccountNumber:    956
  Sequence:         16
  OriginalVesting:  5000000000muon
  DelegatedFree:    10027037768muon
  DelegatedVesting: 
  EndTime:          1518652800 

3. **ran delegate command:** _gaiacli tx staking delegate cosmosvaloper1ktcwmkrgamuhfqm78mwy0py8a0uy5mddhkn0hg 150000000muon --from=syncnode --chain-id=gaia-13001 --trust-node=true --gas=auto --gas-adjustment=1.1_

check the error message here: https://pastebin.com/JiMuSHZ3

**Comment by uditvira** [comment]
Closing stale issue. Please see the readme for current testnet details.
