### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by zhuliting** [cosmos/testnets#142]
hello, I found the link  https://cosmos.network/docs/gaia/join-testnet.html not found from page https://github.com/cosmos/testnets#getting-started,  when I am trying to build a testnet

**Comment by nylira** [comment]
Hi there, the gaia docs have moved to https://hub.cosmos.network/docs/join-testnet.html

**Comment by marbar3778** [comment]
changed this on the readme in #154 , closing this issue
