### ISSUE TITLE
Failed to start testnet: invalid coin denomination

### ISSUE THREAD

**Issue by kosolapov** [cosmos/testnets#144]
```bash
gaiad start
I[2019-07-16|14:16:55.684] Starting ABCI with Tendermint                module=main 
panic: [{"msg_index":"0","success":false,"log":"{\"codespace\":\"staking\",\"code\":102,\"message\":\"invalid coin denomination\"}"}]
```
cosmos-sdk: 0.34.7
Configuration files: [config.toml](https://raw.githubusercontent.com/tendermint/testnets/master/gaia-3006/gaia/config.toml) and [genesis.json](https://raw.githubusercontent.com/tendermint/testnets/master/gaia-3006/gaia/genesis.json)

**Comment by marbar3778** [comment]
We have moved on to a new version of Gaia for the testnet. This error is not applicable anymore. @kosolapov If you run into a issue, you can tag me here or message me in telegram: (@tacoturtle)
