### ISSUE TITLE
[Gaia-13005] Start_height not reset to zero

### ISSUE THREAD

**Issue by dlguddus** [cosmos/testnets#148]
## Summary of Bug

There exists some validators who missed consecutive 5k blocks but not going to jail.
It looks like the downtime judge is in a vacation.

## Version

gaia-13005

## Steps to Reproduce

1. kill a validator
2. wait for 5k blocks
3. validator still alive in validator set.

## Evidence

https://hubble.figment.network/cosmos/chains/gaia-13005/validators/0E2AD63BC5ED6D7537C547A1F24B5C8F311640BE

I expect the bug is from "start_height" of signing_info below.

start_height: 248651
index_offset: 57505
jailed_until: 1970-01-01T00:00:00Z
tombstoned: false
missed_blocks_counter: 5000

https://github.com/cosmos/cosmos-sdk/blob/a922dad3468b4695e2ad7562d71cfc0ed87da328/x/slashing/keeper.go#L200

> minHeight := signInfo.StartHeight + k.SignedBlocksWindow(ctx)
> maxMissed := k.SignedBlocksWindow(ctx) - k.MinSignedPerWindow(ctx)
> 
> if height > minHeight && signInfo.MissedBlocksCounter > maxMissed
> 

StartHeight is 248651 which is from last chain but the height in gaia-13005 started from zero.
So there exists inconsistency in above definition of minHeight causing failure of downtime judgement.

https://github.com/cosmos/cosmos-sdk/blob/68c2201bbf8c79378db73c6ab9e153bef80642fc/simapp/export.go#L162

I guess this should have been done before distributing genesis.json

"WeStaking" first reported this issue to B-Harvest and B-Harvest analyzed

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by jackzampolin** [comment]
This is because I forgot to use the `--for-zero-height` flag when exporting. It is not an issue with the software.
