### ISSUE TITLE
Commission rates haven't been kept in gaia-13006

### ISSUE THREAD

**Issue by kwunyeung** [cosmos/testnets#155]
## Summary of Bug

The commission rates of validators haven't been kept from `gaia-13005` to `gaia-13006`. If the validators haven't updated the commission rates in `gaia-13006`, they all become this

```
      "commission_rates": {
        "rate": "0.000000000000000000",
        "max_rate": "100.000000000000000000",
        "max_change_rate": "0.000000000000000000"
      },
```
not sure if there is issue in state export.

## Version

v2.0.0-rc1

## Steps to Reproduce

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
@marbar3778 @kwunyeung  thoughts on how to approach fixing rates? Should we start a new testnet with same/current Gaia version, exported state and fix commission values?

**Comment by marbar3778** [comment]
yea this would be the only option unless we start fresh, new genesis.

**Comment by kwunyeung** [comment]
Yes, seems only can be fixed with a fresh start.

**Comment by uditvira** [comment]
Closing stale issue.
