### ISSUE TITLE
Failed to start testnet gaia-13007

### ISSUE THREAD

**Issue by ruanqunfeng** [cosmos/testnets#175]
![image](https://user-images.githubusercontent.com/15098545/71335180-6c37f380-257c-11ea-8a06-aa9b573c4c81.png)
panic: {"codespace":"sdk","code":9,"message":"account cosmos1lkm3wh4qurc4j2mhk5x77qputnx0lq36l8mzw9 does not exist: unknown address"}

**Comment by alexanderbez** [comment]
Verify you're on the correct version and have the correct genesis hash.
