### ISSUE TITLE
evidenceParams.MaxAgeNumBlocks must be greater than 0. Got 0

### ISSUE THREAD

**Issue by randomshinichi** [cosmos/testnets#179]
Trying to join gaia-13007 with gaiad 0.0.0-131-g090c545

```
shinichi@asuka:~/.gaiad gaiad start
I[2020-01-23|20:24:43.985] starting ABCI with Tendermint                module=main 
ERROR: Error reading GenesisDoc at /home/shinichi/.gaiad/config/genesis.json: evidenceParams.MaxAgeNumBlocks must be greater than 0. Got 0

```

**Comment by marbar3778** [comment]
please try using v2.0.4 i believe your genesis will be that of 0.33 which is not on the testnet currently

**Comment by alexanderbez** [comment]
Testnet is running on the 2.x.x line. The snippet you posted shows that you're running on a newer and invalid version.
