### ISSUE TITLE
no Go files in /Users/{me}/go/src/github.com/cosmos/cosmos-sdk

### ISSUE THREAD

**Issue by okwme** [cosmos/testnets#18]
result of `go get github.com/cosmos/cosmos-sdk` from readme instructions:
```
can't load package: package github.com/cosmos/cosmos-sdk: no Go files in /Users/{me}/go/src/github.com/cosmos/cosmos-sdk
```

**Comment by ebuchman** [comment]
Not a real error, but we should clarify in the readme that folks can ignore it. Or else we have to tell them to use `mkdir` and `git clone` ...

**Comment by okwme** [comment]
didn't realize it was just a warning 👍
