### ISSUE TITLE
The gaia testnet node synchronisation Error?

### ISSUE THREAD

**Issue by osiz-blockchainapp** [cosmos/testnets#181]
While starting the gaia test node version (gaia-13007) it throws outdated peers connection.

**Error**

`I[2020-02-04|16:19:48.034] starting ABCI with Tendermint                module=main 
E[2020-02-04|16:19:49.297] dialing failed (attempts: 1): auth failure: conn.ID (2a1ddf5a0e44c24a914b00e6c00955d4fbe440d6) dialed ID (444d209bd0f89d7bf18cf389a74872e7082b237e) mismatch module=pex addr=444d209bd0f89d7bf18cf389a74872e7082b237e@44.230.205.153:26656
E[2020-02-04|16:19:49.308] Stopping peer for error                      module=p2p peer="Peer{MConn{51.68.102.106:26656} 30e46db6f9e6f5f19d1c08785faec03616024759 out}" err=EOF
E[2020-02-04|16:19:49.333] Stopping peer for error                      module=p2p peer="Peer{MConn{207.180.204.112:26656} 055a315b20c847813535d7c2b4cedba5756e3d79 out}" err=EOF
E[2020-02-04|16:19:49.560] Stopping peer for error                      module=p2p peer="Peer{MConn{18.217.97.195:26656} 04c28a44dd4eac4961c748bbe5451f7cdd12205c out}" err=EOF
E[2020-02-04|16:19:49.914] Stopping peer for error                      module=p2p peer="Peer{MConn{51.68.102.106:26656} 30e46db6f9e6f5f19d1c08785faec03616024759 out}" err=EOF
E[2020-02-04|16:19:49.977] Stopping peer for error                      module=p2p peer="Peer{MConn{207.180.204.112:26656} 055a315b20c847813535d7c2b4cedba5756e3d79 out}" err=EOF
E[2020-02-04|16:19:50.434] Stopping peer for error                      module=p2p peer="Peer{MConn{18.217.97.195:26656} 04c28a44dd4eac4961c748bbe5451f7cdd12205c out}" err=EOF
E[2020-02-04|16:19:50.554] Stopping peer for error                      module=p2p peer="Peer{MConn{51.68.102.106:26656} 30e46db6f9e6f5f19d1c08785faec03616024759 out}" err=EOF
E[2020-02-04|16:19:50.663] Stopping peer for error                      module=p2p peer="Peer{MConn{207.180.204.112:26656} 055a315b20c847813535d7c2b4cedba5756e3d79 out}" err=EOF
E[2020-02-04|16:19:51.166] Error dialing peer                           module=p2p err="auth failure: conn.ID (2a1ddf5a0e44c24a914b00e6c00955d4fbe440d6) dialed ID (444d209bd0f89d7bf18cf389a74872e7082b237e) mismatch"
E[2020-02-04|16:19:51.182] Stopping peer for error                      module=p2p peer="Peer{MConn{51.68.102.106:26656} 30e46db6f9e6f5f19d1c08785faec03616024759 out}" err=EOF
E[2020-02-04|16:19:51.255] Stopping peer for error                      module=p2p peer="Peer{MConn{207.180.204.112:26656} 055a315b20c847813535d7c2b4cedba5756e3d79 out}" err=EOF
E[2020-02-04|16:19:51.268] Stopping peer for error                      module=p2p peer="Peer{MConn{18.217.97.195:26656} 04c28a44dd4eac4961c748bbe5451f7cdd12205c out}" err=EOF
E[2020-02-04|16:19:51.721] Stopping peer for error                      module=p2p peer="Peer{MConn{51.68.102.106:26656} 30e46db6f9e6f5f19d1c08785faec03616024759 out}" err=EOF
E[2020-02-04|16:19:51.824] Stopping peer for error                      module=p2p peer="Peer{MConn{207.180.204.112:26656} 055a315b20c847813535d7c2b4cedba5756e3d79 out}" err=EOF
E[2020-02-04|16:19:52.099] Stopping peer for error                      module=p2p peer="Peer{MConn{18.217.97.195:26656} 04c28a44dd4eac4961c748bbe5451f7cdd12205c out}" err=EOF
E[2020-02-04|16:19:52.272] Stopping peer for error                      module=p2p peer="Peer{MConn{51.68.102.106:26656} 30e46db6f9e6f5f19d1c08785faec03616024759 out}" err=EOF
E[2020-02-04|16:19:52.453] Stopping peer for error       `

how to resolve this error? can u give possible solution.

**Comment by lcgogo** [comment]
I[2020-03-01|04:11:57.245] starting ABCI with Tendermint                module=main
E[2020-03-01|04:11:58.747] Stopping peer for error                      module=p2p peer="Peer{MConn{18.217.97.195:26656} 04c28a44dd4eac4961c748bbe5451f7cdd12205c out}" err=EOF

same

**Comment by zebpay-peswani** [comment]
same error

**Comment by uditvira** [comment]
Closing stale issue. Please see the readme for current testnet details.
