### ISSUE TITLE
Add more info in README and some links broken

### ISSUE THREAD

**Issue by wimel** [cosmos/testnets#185]
I think it should be a good option to add the `sha256sum` of  the [genesis](https://github.com/cosmos/testnets/blob/master/gaia-13k/13007/genesis.json) for [gaia-13007](https://github.com/cosmos/testnets#testnet-status). The correct `sha256sum` is:
```
ff4a7dd6249c29e54b02fd6e606651614bddbd3cf96109e1540090694fbcfb40
```

-The link to the docs in [README](https://github.com/cosmos/testnets#getting-started) redirect to a [`Page Not Found`](https://hub.cosmos.network/docs/join-testnet.html) web, is the correct link [this](https://hub.cosmos.network/master/gaia-tutorials/join-testnet.html)?

_Thanks to `@D00hanPijo` in the [Spanish Telegram group of Cosmos](https://t.me/Cosmos_Network_ES)_

**Comment by uditvira** [comment]
Closing stale issue. Please see the readme for current testnet details.
