### ISSUE TITLE
synced data delay in my gaia-5000 node

### ISSUE THREAD

**Issue by shenzhun** [cosmos/testnets#22]
os: ubuntu 16.04 aws, C5.xlarge instance(4 core, 8G RAM)
version: 0.16.0-dev-7ef5e90
testnet: gaia-5000
account balance: 0

I set my gaia-5000 node two days ago. When the syncing status was false, but the block data in my node was seriously delayed. If I restarted my gaiad service, it would download the block data quickly,  it slowed down the speed again after a few minutes. I also checked the gaiad running log, but found no error.

**Comment by ebuchman** [comment]
How delayed is delayed? The original sync happens fast, and then once caught up it changes to operate at the pace of the consensus. So it should go from 10s or 100s of blocks per second during "fasy sync" to 1 block every few seconds once caught up.

Can you provide more details of what went wrong? 

And have you tried syncing to gaia-5001 with the latest 0.17.3?

**Comment by shenzhun** [comment]
Thanks, I finally found that the gaia-5000 was deprecated, then I set up a gaia-5001. It works now.
