### ISSUE TITLE
Gaia-13007 testnet stopped at 4,789,881

### ISSUE THREAD

**Issue by jun0tpyrc** [cosmos/testnets#258]
no new blocks  ~15 hours ago 
is there new testnet or this is unexpected? (since README in this repo https://github.com/cosmos/testnets#testnet-status still pointing to it)
https://gaia.stake.id/#/

**Comment by okwme** [comment]
This was an older testnet which validators left in favor of newer versioms (bigbang, stargate) before unbonding was completed halting the network.

I'd recommend jumping in the bigbang-testnet and stargate-v040 discord channels for the most up to date information on testnets

sorry about the confusion
