### ISSUE TITLE
Theta testnet Faucet

### ISSUE THREAD

**Issue by asap0208** [cosmos/testnets#306]
Could you give me enough token to test validator node?

address1: cosmos10dxvnqdvm9ppyr84v80lhaha4p979a4skp5rjf
address2: cosmos1mnn6mf005us5xg7qvpxrwf55px2l3glzezug52

Thanks.

**Comment by uditvira** [comment]
sent!

https://explorer.theta-testnet.polypore.xyz/transactions/CCC7771100AB2317F18050600CDA6C41DE9FCDDD0B4812AE350137476CD85586

https://explorer.theta-testnet.polypore.xyz/transactions/E9D506C3E91387118E0222A8F0357E91D879A8D2B765587C3374B2CB56F08334
