### ISSUE TITLE
seems something wrong with devnet/public faucet

### ISSUE THREAD

**Issue by forbaks** [cosmos/testnets#322]
```
curl 'http://sentry.chain-2.rho-devnet.polypore.xyz:8000/request?chain=rho-chain-2&address=cosmosxxxxxxxxx'
```

will get something like below:

```
{"message": "Error: key with address cosmos1axrwq70w5zd4ar60ksnt9cr4642xx337tnu323 not found: key not found", "status": "fail"}
```

**Comment by forbaks** [comment]
also another problem, public testnet faucet link: https://discord.com/channels/669268347736686612/953697793476821092

seems can not be accessed now, is there a new link? thanks

**Comment by ASoTNetworks** [comment]
I have fixed the faucet and it should now give out tokens.

As for the discord link I have tested and it goes to the faucet channel. Have you joined the `Cosmos Network` server?

**Comment by forbaks** [comment]
Thanks, it should be my fault.
