### ISSUE TITLE
The Sha256sum of the binary does not match

### ISSUE THREAD

**Issue by wimel** [cosmos/testnets#374]
Following the steps provided on [Node manual installation](https://github.com/cosmos/testnets/tree/master/replicated-security/noble-1#verify-binary-checksum) and in the [script provided](https://github.com/cosmos/testnets/blob/master/replicated-security/noble-1/join-rs-consumer-1.sh#L42), the `sha256sum` of the binary is:
`7b03c58b2c28f268e84e116bdac0a9067df7b6b015ee898e84b13313263ec1e0 `  which is not as expected,  using: `go version go1.18.5 linux/amd64`

If you use `go version go1.19.4 linux/amd64` as it says in the [installation script](https://github.com/cosmos/testnets/blob/master/replicated-security/noble-1/join-rs-consumer-1.sh#L29) the `sha256sum` of the binary is `c4f91630865fe2b10af730abf37c8fec64bc5ea0085f2f70e3f5a71e944abe64`

- Steps to reproduce:
```
git clone https://github.com/strangelove-ventures/noble.git
cd noble
git checkout v0.2.0
make install
```
 
The only way to get the correct `sha256sum` has been to [download the binary](https://github.com/cosmos/testnets/blob/master/replicated-security/noble-1/nobled-linux-amd64) and give it permissions to run and then check the `sha256sum`.

I think it would be a nice option to include in the installation steps a preferred version of `go` and the `sha256sum` of the binary with that version of `go`, for some people is better to compile the binaries ourselves.

_Thanks in advance!._

**Comment by dasanchez** [comment]
Hi! Thanks for bringing this up-
Even if we used the same version of go, it's not guaranteed the checksum would match between two different systems. The current process of verifying the binary is not perfect- like you mentioned, the only way to get the same checksum is to download the published binary and calculate the hash with it.
Some people have suggested publishing a container-based build system that creates reproducible binaries, but it's not something we are working on at this time.
