### ISSUE TITLE
Expose: grpc-web endpoint

### ISSUE THREAD

**Issue by jlm0** [cosmos/testnets#390]
Hello,
I need the grpc-web endpoint but noticed that only REST,RPC, and gRPC endpoints are being exposed on the theta-testnet nodes. Is it possible to expose the grpc-web server from port :9091 as followed:
https://grpc-web.<node-name>.theta-testnet.polypore.xyz:443

Please let me know who is the best point of contact for this.
Thanks!

**Comment by dasanchez** [comment]
Hi! Sorry, late than never :)
Do you still require the grpc-web server? We could open one in a sentry.

**Comment by dasanchez** [comment]
`theta-testnet-001` is being deprecated as of Dec 1, please open another issue if you would like us to expose additional services in the `provider` network.
