### ISSUE TITLE
Discord link does not work

### ISSUE THREAD

**Issue by mrakus-sofomo** [cosmos/testnets#393]
Hi
`https://discord.com/channels/669268347736686612` does not work. Is there any other way to add test funds to my wallet?

**Comment by deniseyu** [comment]
@mrakus-sofomo what was the error message you encountered?

**Comment by dasanchez** [comment]
@mrakus-sofomo where are you getting the link from? This should take you to the relevant Discord channel:
https://github.com/cosmos/testnets/blob/0ff1de9acaf9b4b443fd853f5cd053023561a1a9/public/README.md?plain=1#L57

**Comment by ductrinhhuu** [comment]
hello,
how can I ask for help on voting proposal on testnet?
