### ISSUE TITLE
"gaiacli stake create-validator" example contains wrong flag (--address-candidate)

### ISSUE THREAD

**Issue by Liamsi** [cosmos/testnets#52]
`ERROR: unknown flag: --address-candidate`
see also https://github.com/cosmos/cosmos-sdk/issues/1177

**Comment by shenzhun** [comment]
I just checked the source code, it should be --address-validator.

**Comment by nylira** [comment]
I have fixed this in https://github.com/cosmos/cosmos-sdk/pull/1212
