### ISSUE TITLE
` join-release-testnet.sh` improvements

### ISSUE THREAD

**Issue by rootulp** [cosmos/testnets#620]
## Context

I'm trying to join Cosmos Hub testnet by using join-release-testnet.sh

## Problems

1. The script isn't executable. To fix: `chmod +x join-release-testnet.sh`
2. The script automatically downloads the amd64 version when my machine is arm64. Consider downloading the binary that is applicable for the user's current platform. You can check the platform via `uname -a` and parse the output. For posterity, if you're hitting this, you'll see an error like:

```
root@rootulp-arabica:~/testnets/release# journalctl -fu gaiad.service
Aug 27 14:45:28 rootulp-arabica systemd[1]: Started Gaia service.
Aug 27 14:45:28 rootulp-arabica systemd[105242]: gaiad.service: Failed to execute /root/go/bin/gaiad: Exec format error
Aug 27 14:45:28 rootulp-arabica systemd[105242]: gaiad.service: Failed at step EXEC spawning /root/go/bin/gaiad: Exec format error
Aug 27 14:45:28 rootulp-arabica systemd[1]: gaiad.service: Main process exited, code=exited, status=203/EXEC
Aug 27 14:45:28 rootulp-arabica systemd[1]: gaiad.service: Failed with result 'exit-code'.
```

**Comment by dasanchez** [comment]
Hi @rootulp ! Thanks for the input, we'll add a note in the docs so people know that the URL in that block should be modified to suit the relevant architecture.
