### ISSUE TITLE
rename steak to 'testnet-atoms' or something much less confusing

### ISSUE THREAD

**Issue by jbibla** [cosmos/testnets#67]
## Summary
User of Voyager don't understand what steak is. It is confusing, unhelpful, and yet another new thing that users need to wrap their heads around. We don't want to make too many accommodations for testnet specific items (like explaining what steak is) and this will help people understand the network and Voyager better.

"Oh, this is how it will work for Atoms" - users who use testnet-atoms pre launch.

## Proposal
Please change the staking token on testnets from steak to testnet-atoms or something equally as clear and self explanatory.

**Comment by zmanian** [comment]
@sunnya97 What do you think?

**Comment by sunnya97** [comment]
Shrug.  They were supposed to be called fermions, but they "accidentally" got called steak because I did that as a joke in the `simplestake` module, and then we didn't want to change all the docs we had.  

Although, we might not want to have a token on a testnet that has the word `atom` in it, because that might cause confusion or scams.  @jaekwon

**Comment by nylira** [comment]
We're having an upcoming major event called "Game of Steaks" or "Testnet of Steaks" that has artwork revolving around pieces of meat. The validator community has embraced the name already -- they send and receive steak constantly over the course of months of testnets.

![space-cowboy-cowgirl](https://user-images.githubusercontent.com/172531/43943086-dbb272da-9cac-11e8-9cba-3d34ee37e6c4.jpg)

Cosmos China has translated the post using the same "steak" terminology (and emoji) https://forum.cosmos.network/t/cosmos-cosmos-is-rolling-out-a-game-called-a-testnet-of-steaks/408

I agree with Sunny that we don't want to cause confusion by releasing any token with the name "Atom" in it before mainnet.

I think it may just be too late to change it right now.

**Comment by jbibla** [comment]
> I think it may just be too late to change it right now.

you might be right.

**Comment by zmanian** [comment]
We are definitely calling the staking token for Game of Steaks `steak`

**Comment by cwgoes** [comment]
Agreed that this is confusing, but I think changing it now will likely be *more* confusing.

**Comment by jbibla** [comment]
ok there seems to be consensus around using `steak` for game of steaks. 

is it too late to change `steak` to `testnet-atoms` on future testnets? and if we do this, does is it complicate / add confusion to game of steaks?

**Comment by zmanian** [comment]
it's a trivial change. But @jaekwon really wanted us not to use the word `atom` in testnets

**Comment by jbibla** [comment]
interesting. @jaekwon is there some reason that hasn't been addressed in this thread or is there a thread somewhere else I can look to for understanding?

based on some very shallow research it would appear to me that ethereum testnets use `ETH` which was a little surprising.

it would seem to me that `testnet-atoms` would be relatively clear and self explanatory as opposed to `steak` which is confusing (it is a play on words) and not-self-explanatory. 

we don't need to drag this out - but if it's a trivial change and there aren't any objections to how confusing it will be for testnet participants going forward - i think it might be worth changing.

**Comment by zmanian** [comment]
Blocked on https://github.com/cosmos/cosmos-sdk/issues/2097

I vote for reverting `gaia-8000` to steak and proceeding

**Comment by uditvira** [comment]
Closing stale issue.
