### ISSUE TITLE
Question ?

### ISSUE THREAD

**Issue by sarmel** [cosmos/testnets#81]
How to deploy a Testnet?

**Comment by alexanderbez** [comment]
@sarmel see [here](https://github.com/cosmos/cosmos-sdk/tree/develop/networks/local)

**Comment by sarmel** [comment]
Thanks

**Comment by Bha91** [comment]
> @sarmel see [here](https://github.com/cosmos/cosmos-sdk/tree/develop/networks/local)

404-page not found
