### ISSUE TITLE
Allocate a large supply of a token for tx testing

### ISSUE THREAD

**Issue by mattharrop** [cosmos/testnets#83]
We need to start generating transaction volume on testnets.  To facilitate, I suggest creating a token for this purpose, and allocate a large number to each genesis validator.  

My suggestion is to call this token a `nutrino`, and allocate 1,000,000 to each validator.

**Comment by jackzampolin** [comment]
Really like this idea @mattharrop. Thanks for opening the issue. I think we should incorporate this in the `gaia-9002` genesis. Thoughts @zmanian?

**Comment by zmanian** [comment]
Sure will do for gaia-9002

**Comment by adrianbrink** [comment]
Fantastic. How are we generating the genesis file for gaia-9002?
